server:
  port: 8080
  servlet.context-path: /api-backend_architecture
backend_architecture:
  app:
    jwtSecret: backend_architectureKey123
    jwtExpirationMs: 86400000
spring:
  application:
    name: api-backend_architecture
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    database:
      url:local: